swagger: "2.0"
info:
  description: "serverless util functions built on top of path of exile trade api"
  version: "1.0.0"
  title: "ac-sniper api"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "ac-sniper-tiirent.vercel.app"
basePath: "/api"
tags:
- name: "query"
  description: "query functions"
- name: "item"
  description: "item functions"
- name: "result"
  description: "result functions"
schemes:
- "https"
paths:
  /query/{urlId}:
    get:
      tags:
      - "query"
      summary: "find query by urlId"
      description: "fetch query using the zWviEkd at the end of poe url"
      produces:
      - "application/json"
      parameters:
      - name: "urlId"
        in: "path"
        description: "ID of item to get query for"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Query"
        "500":
          description: "something not right"
  
  /item:
    post:
      tags:
      - "item"
      summary: "get itemId results from query"
      description: "Returns a list of itemIds that match query"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "query in body"
        required: true
        schema:
          $ref: "#/definitions/Query"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Item"
        "500":
          description: "something not right"
  /result/{queryId}:
    post:
      tags:
      - "result"
      summary: "get item listings from itemIds"
      description: "returns the listings (with whisper + details) from itemIds"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "queryId"
        in: "path"
        description: "queryId ID of items to get query for (not sure if this has to match)"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "itemId array in body"
        required: true
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/Listing"
        "500":
          description: "something not right"
          
definitions:
  Query:
    type: object
    properties:
      name:
        type: string
        example: "Nebulis"
      type:
        type: string
        example: "Void Sceptre"
      stats:
        type: array
        items: 
          type: object
      status:
        type: string
        example: "any"
      filters:
        type: object
  Item:
    type: object
    properties:
      id:
        type: string
      complexity:
        type: integer
      result:
        type: array
        items: 
          type: string
      total:
        type: integer
  Listing:
    type: object
    properties:
      id:
        type: string
      listing:
        type: object
        properties:
          whisper:
            type: string
          price:
            type: object
            properties:
              amount:
                type: integer
              currency: 
                type: string
      
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"